### ISSUE TITLE
文档整理

### ISSUE THREAD

**Issue by wmn7** [Xivid/10043#2]
- [x] 把总的文档拆开
- [x] 制作一个目录

**Comment by Xivid** [comment]
征求讨论：是否有必要把文档整理成readthedocs.io的结构，通过GitHub协作编辑？

**Comment by wmn7** [comment]
我觉得暂时可以不需要。GitHub协作编辑可能没有腾讯文档方便，还是我们统一编辑较好。（我个人认为啊）

**Comment by Luodian** [comment]
我也认为不需要，直接用腾讯文档就好了。
